[package]
name = "floatilla"
version = "0.2.0"
authors = ["Phoenix Kahlo <kahlo.phoenix@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.num-traits]
version = "0.2"
default-features = false

[features]
default = ["std"]
std = ["num-traits/std"]